language: java
jdk:
- openjdk11
services:
- docker
before_install:
- chmod +x mvnw
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker pull openjdk:11-jre-slim-sid
script:
- "./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install"
- "./mvnw heroku:deploy jib:build -P deploy-heroku,deploy-docker"
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    secure: K/C3899vWWKQ2y036JrtWG9DuYxwFuwNWZ+G5LlGOX0sBQB40XaEoPz9b+PmXdilg1NKsQJVeEN82uVILG5t8JSNNjZW3Bdl10hjoeujA9MdFgGIvmNVgZceGqfS+IGTcz4j2XQRbWLCYhphBTI+Mv8qP54fvL4oXvXLFC094/1sjJ85vFQtEYW8tNzWePkD2cF85Cj+M9CoxQHwANWs34wcbZYXilxLOavJAehH08udhwqtn8HiOzJc7+c4iqWNbNp7oDkmW61X8DK9HbPuRUnWR44qimGBR7J5wCJFQXO3lOaaGQJ88bOmY3O10Y/AsQ4bEa6muO+iZjG7G6wlCWplv2qVQBmxNvNx9t0Fetp73zjXtKVSor5HREgxLLm5lcW1KgpBOuZjdsK2CRArktFE5Tw9wai5Uo9u8vxvXY0pvg2JUIaaypNqraFmimIdL0nZ0Fx9ySN01McFP7bNCzeUK4K3lVCwSBUdBwhKxw3FhWSk4GQK9LsJnG53uHgI9GfhPuMkiIgbLxy120wQwIrDCSyFAqcuDrKHHb0amQPNhYj3m48khStqGoUCtX0wLo36br1zE+X8HJnd/iK6dc69JkCTZB5gDReaDsONJNyhGcICQdnsSOwtYkKwACv3rNPMbg9Poo1w5JXnQBiwtU7QcREffHZC7rywv0Gn7f8=
    on_success: always 
    on_failure: always