language: java
jdk:
- openjdk11
services:
- docker
before_install:
- chmod +x mvnw
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker pull openjdk:11-jre-slim-sid
script:
- "./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install"
- "./mvnw heroku:deploy jib:build -P deploy-heroku,deploy-docker"
after_success:
- bash <(curl -s https://codecov.io/bash)

if: branch = master
notifications:
  slack:
    secure: CrImJ9dHy2+hnwi64zjkyHXWCdQIkNOhQs408cqpk1/XsuUoUSU3TeYdQ9wH+EKKmSlSkquc+iXbza4b3MV+ULgitY3Ha7k4wFMflgUuNgBvyIlaND4rrSQuzlHDpTZH4YB9qyhjJznHGf86bBHTtzxYAd+Y9PjhHJ7sgqbpmkxni/jEYx4OntoplV4lzfJ+CrdkCLHvz9lsfqZwNfyrtC1aPcvgr25AdTgne56yyz44zxknvUfJHaEBGY3NNc2DBrnZhnhK0B/thsUuZUyU1WCIEs+kXKaPAttnISZDsSZn2l43OHnQQOLqspY7SVYherCSpxt60owzmNlENCON6gRhUyyEVs0rUNxtTT4HoOhO09e/3vtjNK7Vh9jAgvNAoGGD5vW/7maaulgTwlDNu8DJ5cVopPMBFiGbQgFCn/FiVozLT2UudqPSLUB+qxRLghEXa5JSinhFXbOYPJE3ypZDSLncGGtJBjn+B/Ry/l6uNLyAQ7oFdeZHZWBzMZC4YhMBNitZOnJtW+1DUOS6514KC+XvhrDXVkm2X0XoYz7rtR0VP6Ias7O6e27fObUYlIp/Ij8Ye8wUd/K+BIZ8XhBW0/pIFkFzMYE51SY+Njaoax8XgzQAAA9LXZgDsLib5gv0xuU3A9ICVoQMeZdDZK7C1eHD0GkJrgZG6TS4UnU=
    on_success: always
    on_failure: always
    template:
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Message: %{message}"